EXTRA_INCLUDEPATH += C:\\openssl-1.0.2j-64bit-release-DLL-VS2015\\include
EXTRA_LIBDIR += C:\\openssl-1.0.2j-64bit-release-DLL-VS2015\\lib
QT_CPU_FEATURES.i386 = sse sse2
QT.global_private.enabled_features = sse2 alloca_malloc_h alloca avx2 dbus gui network sql testlib widgets xml
QT.global_private.disabled_features = private_tests android-style-assets alloca_h dbus-linked libudev posix_fallocate reduce_exports reduce_relocations release_tools stack-protector-strong system-zlib
QT_COORD_TYPE = double
CONFIG += sse2 aesni sse3 ssse3 sse4_1 sse4_2 avx avx2 compile_examples f16c largefile precompile_header rdrnd shani x86SimdAlways
QT_BUILD_PARTS += libs tools
QT_HOST_CFLAGS_DBUS += 
